### ISSUE TITLE
DOMException: Failed to execute 'atob' on 'Window'

### ISSUE THREAD

**Issue by bcomnes** [netlify/gotrue-js#13]
Its been reported in a few different cases that gotrue-js will sometimes throw with certain user accounts when logging in with authentication providers like github.

![console](https://user-images.githubusercontent.com/166301/32184372-40daf72e-bd59-11e7-886c-88740c910df1.PNG)

We should probably handle this error in gotrue-js, but also hunt down the root cause.

A workaround is deleting the troubled account from the gotrue instance and re-inviting / recreating it.

> Removing myself and re-adding to Identity. Maybe there's something up with the fact that I was invited before GitHub login was enabled, or before the widget was added...

**Comment by fool** [comment]
a customer saw this again today - bug persists :)

**Comment by bcomnes** [comment]
Added it to the product roadmap as an actionable task

**Comment by manspeterson** [comment]
having the same problem. it has to do with atob's inability to work with non-ascii characters. really appreciate if this could get prioritized. 

https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings

**Comment by manspeterson** [comment]
...or something during the jwt generation since the token i receive when this happen include e.g. a "_" character.

**Comment by bcomnes** [comment]
Closed by https://github.com/netlify/gotrue-js/pull/18

**Comment by pukhalski** [comment]
Hi guys, is this resolved already? We still have people facing this issue although the latest version is being in use.

**Comment by ranjiit12** [comment]
I have the same issue. What's solution?

**Comment by bcomnes** [comment]
Issue should be resolved at this point.  Open a new issue with a reproducible scenario and details of where its occuring and we can investigate.

**Comment by bcomnes** [comment]
Preemptively, some browsers require a polyfill that https://github.com/davidchambers/Base64.js can provide.  You can include that if you want.  Perhaps we should document this.

**Comment by mcamauryasatish** [comment]
I am also getting the same issue in Firebase.

**Comment by bcomnes** [comment]
@mcamauryasatish This issue is resolved, but some browsers require a polyfill. See https://github.com/netlify/gotrue-js/issues/13#issuecomment-409287335

If that does not work for you, please open a new issue with a way to reproduce what you are seeing.
