### ISSUE TITLE
gotrue.js does not save nf_jwt cookie when logging in via external provider

### ISSUE THREAD

**Issue by futuregerald** [netlify/gotrue-js#15]
After logging in using a username and password, gotrue saves the JWT in a cookie named `nf_jwt`, in addition to storing the user object in the browser's localstorage. However when you login using an external provider it only saves the user to localstorage, it does not save the JWT in a cookie. I tested logging in via Google and Github and had the same experience with both.

The issue this causes is that you can't use JWT based redirects on Netlify when logging in via an external provider.

**Comment by safoo** [comment]
+1 on this issue. Took countless hours to test and observe same as @futuregerald and I was expecting the cookie to be created based on all the documentation I read.

**Comment by sw-yx** [comment]
this seems to be because the external providers don't provide a `Set-Cookie` header so we'll have to fake it ourselves.  PR welcome to do it.

@safoo may i ask why exactly does it matter between localstorage and cookies?

**Comment by safoo** [comment]
@sw-yx I wasn't able to get the role based redirects to work using external provider until there was a cookie saved

**Comment by sw-yx** [comment]
yowzer. good to know.

**Comment by sw-yx** [comment]
fixed in `netlify-identity-widget@1.5.4`
![idetntitywidget](https://user-images.githubusercontent.com/6764957/58144240-9e1a5d80-7c1b-11e9-93fd-85962f6d3d8c.gif)

**Comment by sw-yx** [comment]
i have updated `react-netlify-identity-widget@0.0.26` as well
