### ISSUE TITLE
signup data argument NOT optional

### ISSUE THREAD

**Issue by MatthewPardini** [netlify/gotrue-js#158]
The data argument is optional in documentation, but the js client requires it. This creates a problem using typescript.

**Comment by erezrokah** [comment]
Hi @MatthewPardini, do you mind following the issue template?
https://github.com/netlify/gotrue-js/issues/new?assignees=&labels=&template=bug_report.md&title=

That will provide more context on the issue you're having and make sure we have enough information to resolve it.

I'm guessing there is some kind of issue with our Types, probably with this line:
https://github.com/netlify/gotrue-js/blob/d6297653cb57d2fde87fc858a53d4682b28dae9c/index.d.ts#L30

but can't be sure.

**Comment by MatthewPardini** [comment]
Correct. I filed the bug as requested here #159

**Comment by erezrokah** [comment]
Thank you, closing this issue in favour of https://github.com/netlify/gotrue-js/issues/159
