### ISSUE TITLE
Rename repository description

### ISSUE THREAD

**Issue by Jolg42** [netlify/gotrue-js#2]
<img width="294" alt="screenshot 2017-03-20 at 14 39 37" src="https://cloud.githubusercontent.com/assets/1328733/24102115/32e390ce-0d7b-11e7-9bfd-3d3b74e05a47.png">

Changing the repository's description to "JavaScript client library for Gotrue API" would achieve the renaming ;)

**Comment by calavera** [comment]
Fixed, thanks!
