### ISSUE TITLE
Getting errors when trying to login using Google authentication

### ISSUE THREAD

**Issue by bjrn** [netlify/gotrue-js#22]
Seems like an extra `/` sneaked into tokenResponse …
the script tries to get access_token through this line:

```
tokenResponse.access_token.split(".")...........
```

but `access_token` is being sent as `/access_token` in the tokenResponse object, thus resulting in a script error:
![image](https://user-images.githubusercontent.com/151166/35966506-4427fd14-0cbe-11e8-83d6-6776459585d6.png)

Here's the `responseToken`
![image](https://user-images.githubusercontent.com/151166/35966779-1df11404-0cbf-11e8-9d2f-02cc1a3c7c46.png)

**Comment by futuregerald** [comment]
I was able to recreate this on the users site.
For netlify debug:
https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/14516957002

**Comment by futuregerald** [comment]
This issue is also affecting:
https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/14528083083

**Comment by bcomnes** [comment]
This was an issue with the widget.  It should be working with https://github.com/netlify/netlify-identity-widget/releases/tag/v1.4.11

If you are using the script tag, you are already updated.
