### ISSUE TITLE
Update user metadata - Netlify Identity

### ISSUE THREAD

**Issue by sidati** [netlify/gotrue-js#44]
Hi Guys,
Im trying to give my users the ability to update there meta data such as full name and phone number, it is possible to create the meta data using `signup` action but update them is not possible, i can only update the password and the email, is that an expected behavior or am i doing something wrong ? Hope someone can help 🤓

**Comment by bcomnes** [comment]
You can update the user metadata client side.  App metadata has to be updated from a secure environment like a lambda function. See https://github.com/futuregerald/identity-test-functions for an example.

**Comment by smuriu** [comment]
The API documentation is misleading. To successfully write user metadata, submit a request with the `user_metadata` key (not the `data` key as described in the docs). Please see companion gotrue issue [#213](https://github.com/netlify/gotrue/issues/213).

**Comment by tjbo** [comment]
^ Agreed, the docs are total trash.

**Comment by ecupaio** [comment]
So I figured out how to do this with some trial and error and of course no help from the docs. For context, I'm adding a full_name field to the meta data. I'm assuming you have a basic grasp of consts and JSON but please reach out if you need a more detailed example that actually works with a form. 
```
auth
      .signup(email, password, {full_name: fullName})
      .then((response) => {
        setFormStatus('success');
      })
      .catch((error) => {
        console.log('email state: '+email);
      });
```
First, pass the email and password values into the the signup function, then add your user_metadata object: `{full_name: fullName}` You don't need to wrap the custom metadata object in the parent user_metadata. It automatically assumes that's what you're passing through via undocumented Javascript magic. Now that custom user metadata won't actually show in Netlify Identity UI, but rest assured that data value will be stored within the user_metadata object for retrieval in your code.
