### ISSUE TITLE
auth.recover returns server error of 'response is undefined'

### ISSUE THREAD

**Issue by QuantumInformation** [netlify/gotrue-js#68]
You can reproduce this here:

https://svelte-netlify-identity.netlify.com/recover

![image](https://user-images.githubusercontent.com/216566/71164348-2662ee80-224f-11ea-88d7-3efaad0c11dd.png)

Am I calling the code wrong here? : https://github.com/QuantumInformation/svelte-fullstack-starter/blob/master/src/stores/netlifyUserStore.js#L84

It always hits the below catch

**Comment by ljosberinn** [comment]
Can't reproduce - `await goTrue.recover(token)` resolves with a user for me, but only once as the token is invalidated after (which, on a sidenote, makes testing very tedious).

**Comment by QuantumInformation** [comment]
OK I seem to have have fixed it, closing it, if anyone else finds this I will re open.


thx for testing
