### ISSUE TITLE
use nodejs backend verify auth

### ISSUE THREAD

**Issue by derit** [netlify/gotrue-js#70]
in my case, i want to verify current user auth with backend nodejs

**Comment by luukdv** [comment]
It looks like this is the same issue as: https://github.com/netlify/gotrue-js/issues/46

**Comment by erezrokah** [comment]
Hi @derit, the backend part of `gotrue-js` is https://github.com/netlify/gotrue.

Can you describe your use case in more details (e.g. do you want to verify the user email/password or the token)?

**Comment by derit** [comment]
@erezrokah i just create simple app for verify email using gotrue with nodejs 
step 1 create project, i use yarn and add package gotrue 
step 2 create function confirm or verify email 
just run index.js with nodejs and show error request url fetch 
but i has found a solution, look on [this ](https://github.com/netlify/gotrue-js/issues/46#issuecomment-574535007)comment
