### ISSUE TITLE
Need to update documentation about saving to localstorage

### ISSUE THREAD

**Issue by tedlittledale** [netlify/gotrue-js#72]
This is not in the readme file!
https://github.com/netlify/gotrue-js/pull/23/files

**Comment by willdkp** [comment]
### Oh my god! 
That really needs to be in the docs. Spent a few hours trying to get logged in state to persist between page refreshes. And only stumbling upon this issue got me there.

**Comment by ttntm** [comment]
Indeed, I also just found out about this the hard way due to page refresh logging users out.
