### ISSUE TITLE
Return the same error on login if either email or password is incorrect

### ISSUE THREAD

**Issue by paulrosen** [netlify/gotrue-js#74]
When calling login with a bad email address the message is "No user found with this email" but if it is called with a bad password the message is "invalid password". Isn't this a security problem? A hacker fishing around could try email addresses and see if someone has an account.

**Comment by j-651** [comment]
This is also an open issue for the Netlify Identity Widget - https://github.com/netlify/netlify-identity-widget/issues/225

**Comment by lloydjatkinson** [comment]
This has now been fixed in the linked PR.
